# Generated by Django 5.0.1 on 2024-02-15 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daily',
            new_name='Counter',
        ),
        migrations.RenameField(
            model_name='counter',
            old_name='item',
            new_name='query',
        ),
    ]
